# https://taskfile.dev

version: "3"

dotenv:
  - ".env"

env:
  DSN: "{{.DB_TYPE}}://{{.DB_USER}}:{{.DB_PASSWORD}}@{{.DB_HOST}}:{{.DB_PORT}}/{{.DB_NAME}}?sslmode=disable"

tasks:
  default:
    desc: "Gettings started"
    cmds:
      - task: install
      - task: service:up

  install:
    desc: "Install dependencies"
    cmds:
      - npm install
      - go mod download
      - go install github.com/air-verse/air@latest
      - go install github.com/a-h/templ/cmd/templ@latest
      - go install github.com/pressly/goose/v3/cmd/goose@latest
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

  service:up:
    desc: "Start services"
    cmd: docker compose up -d

  service:down:
    desc: "Stop services"
    cmd: docker compose down

  db:cli:
    desc: "Connect to database using command line interface"
    cmd: docker exec -it sea-salon_postgres psql -U postgres -d {{.DB_NAME}}

  migrate:create:
    desc: "Create new database migration"
    cmd: goose -dir pkg/postgres/migrations create {{.CLI_ARGS}} sql

  migrate:up:
    desc: "Run database migrations"
    cmd: goose -dir pkg/postgres/migrations postgres $DSN up

  migrate:down:
    desc: "Rollback to previous database migration"
    cmd: goose -dir pkg/postgres/migrations postgres $DSN down

  sqlc:
    desc: "Generate SQLC code"
    cmd: sqlc generate

  dev:
    desc: "Start development server"
    cmd: air

  lint:
    desc: "Run linter"
    cmd: golangci-lint run ./...

  build:
    desc: "Build binary"
    cmd: go build -o ./bin/{{.APP_NAME}} ./cmd/main.go
    requires:
      vars:
        - APP_NAME

  start:
    desc: "Start binary"
    cmd: ./bin/{{.APP_NAME}}
    requires:
      vars:
        - APP_NAME

  test:
    desc: "Run tests"
    cmds:
      - go test -v ./... -race -cover -timeout 30s -count 1 -coverprofile=coverage.out
      - go tool cover -html=coverage.out -o coverage.html
