// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	DeleteAccount(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	InsertAccount(ctx context.Context, arg InsertAccountParams) error
	SelectAccountByEmail(ctx context.Context, email string) (Account, error)
	SelectAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	SelectAllAccounts(ctx context.Context, arg SelectAllAccountsParams) ([]Account, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
