// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	DeleteUser(ctx context.Context, id uuid.UUID) error
	InsertUser(ctx context.Context, arg InsertUserParams) error
	SelectAllUsers(ctx context.Context, arg SelectAllUsersParams) ([]User, error)
	SelectUserByEmail(ctx context.Context, email string) (User, error)
	SelectUserByID(ctx context.Context, id uuid.UUID) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
